try:
    from homeassistant.const import EntityCategory
except ImportError:
    # Fallback for testing when homeassistant is not available
    class EntityCategory:
        DIAGNOSTIC = "diagnostic"


DOMAIN = "ha_daikin_altherma4_modbus"
DEFAULT_PORT = 502

SLOW_SCAN_INTERVAL = 30
NORMAL_SCAN_INTERVAL = 5

# Valid Modbus address ranges based on device documentation
MIN_MODBUS_ADDRESS = 1
MAX_MODBUS_ADDRESS = 87

INPUT_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "input_registers")},
    "translation_key": "daikin_altherma_modbus_input_registers",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

HOLDING_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "holding_registers")},
    "translation_key": "daikin_altherma_modbus_holding_registers",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

CALCULATED_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "calculated_sensors")},
    "translation_key": "daikin_altherma_modbus_calculated_sensors",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

DISCRETE_INPUT_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "discrete_input_registers")},
    "translation_key": "daikin_altherma_modbus_discrete_input_registers",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

COIL_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "coil_registers")},
    "translation_key": "daikin_altherma_modbus_coil_registers",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

# Alle Input-Register aus 7.2.2 Daikin Configuration reference guide MMI user interface

INPUT_REGISTERS = [
    # Fehler / Status
    {
        "name": "Unit abnormality",
        "address": 21,
        "unit": None,
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:alert-circle",
        "input_type": "input",
        "register_name": "input_21",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enum_map": {0: "no_error", 1: "fault", 2: "warning"},
        "translation_key": "input_21",
    },
    {
        "name": "Unit abnormality code",
        "address": 22,
        "unit": None,
        "scale": 1,
        "dtype": "string",
        "count": 1,
        "icon": "mdi:alert-circle",
        "input_type": "input",
        "register_name": "input_22",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_22",
    },
    {
        "name": "Unit abnormality sub code",
        "address": 23,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:alert-circle",
        "input_type": "input",
        "register_name": "input_23",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enum_map": {**{i: f"error_{i}" for i in range(100)}, 32766: "no_error"},
        "translation_key": "input_23",
    },
    {
        "name": "3-way valve",
        "address": 37,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:pipe-valve",
        "input_type": "input",
        "register_name": "input_37",
        "entity_category": None,
        "enum_map": {0: "Space heating", 1: "DHW"},
        "translation_key": "input_37",
    },
    # Betriebsarten
    {
        "name": "Operation mode",
        "address": 38,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:thermostat",
        "input_type": "input",
        "register_name": "input_38",
        "entity_category": None,
        "enum_map": {
            0: "None",
            1: "Heating",
            2: "Cooling",
        },
        "translation_key": "input_38",
    },
    # Temperaturen
    {
        "name": "Leaving water temperature PHE",
        "address": 40,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_40",
        "entity_category": None,
        "translation_key": "input_40",
    },
    {
        "name": "Leaving water temperature BUH",
        "address": 41,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_41",
        "entity_category": None,
        "translation_key": "input_41",
    },
    {
        "name": "Return water temperature",
        "address": 42,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_42",
        "entity_category": None,
        "translation_key": "input_42",
    },
    {
        "name": "DHW temperature",
        "address": 43,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_43",
        "entity_category": None,
        "translation_key": "input_43",
    },
    {
        "name": "Outside air temperature",
        "address": 44,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_44",
        "entity_category": None,
        "translation_key": "input_44",
    },
    {
        "name": "Liquid refrigerant temperature",
        "address": 45,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_45",
        "entity_category": None,
        "translation_key": "input_45",
    },
    # Durchfluss
    {
        "name": "Flow rate",
        "address": 49,
        "unit": "L/min",
        "scale": 0.01,
        "dtype": "uint16",
        "icon": "mdi:water-pump",
        "input_type": "input",
        "register_name": "input_49",
        "entity_category": None,
        "translation_key": "input_49",
    },
    {
        "name": "Remote control room temperature (Main)",
        "address": 50,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_50",
        "entity_category": None,
        "translation_key": "input_50",
    },
    # Leistungswerte
    {
        "name": "Heat pump power consumption",
        "address": 51,
        "unit": "W",
        "scale": 10,
        "dtype": "uint16",
        "icon": "mdi:lightning-bolt",
        "input_type": "input",
        "register_name": "input_51",
        "entity_category": None,
        "translation_key": "input_51",
    },
    # Normalbetrieb flags
    {
        "name": "DHW normal operation",
        "address": 52,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:information",
        "input_type": "input",
        "register_name": "input_52",
        "entity_category": None,
        "translation_key": "input_52",
        "enum_map": {0: "Idle/Buffering", 1: "Operation"},
    },
    {
        "name": "Space heating/cooling normal operation",
        "address": 53,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:information",
        "input_type": "input",
        "register_name": "input_53",
        "entity_category": None,
        "translation_key": "input_53",
        "enum_map": {0: "Idle/Buffering", 1: "Operation"},
    },
    # Binary Status Register (30-36)
    {
        "name": "Circulation pump running",
        "address": 30,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:pump",
        "input_type": "input",
        "device_class": "running",
        "register_name": "input_30",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_30",
    },
    {
        "name": "Compressor run",
        "address": 31,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:compressor",
        "input_type": "input",
        "device_class": "running",
        "register_name": "input_31",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_31",
    },
    {
        "name": "Booster heater run",
        "address": 32,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:heater",
        "input_type": "input",
        "device_class": "running",
        "register_name": "input_32",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_32",
    },
    {
        "name": "Disinfection operation",
        "address": 33,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:water-boiler",
        "input_type": "input",
        "device_class": "running",
        "register_name": "input_33",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_33",
    },
    {
        "name": "Defrost/Restart",
        "address": 35,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:snowflake-melt",
        "input_type": "input",
        "device_class": "running",
        "register_name": "input_35",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_35",
    },
    {
        "name": "Hot start",
        "address": 36,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:fire",
        "input_type": "input",
        "device_class": "running",
        "register_name": "input_36",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_36",
    },
    # Sollwerte (Setpoints)
    {
        "name": "Leaving water Main Heating setpoint lower",
        "address": 54,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_54",
        "entity_category": None,
        "translation_key": "input_54",
    },
    {
        "name": "Leaving water Main Heating setpoint upper",
        "address": 55,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_55",
        "entity_category": None,
        "translation_key": "input_55",
    },
    {
        "name": "Leaving water Main Cooling setpoint lower",
        "address": 56,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_56",
        "entity_category": None,
        "translation_key": "input_56",
    },
    {
        "name": "Leaving water Main Cooling setpoint upper",
        "address": 57,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_57",
        "entity_category": None,
        "translation_key": "input_57",
    },
    # Zusätzliche Sollwert-Grenzen
    {
        "name": "Leaving water Add Heating setpoint lower",
        "address": 58,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_58",
        "entity_category": None,
        "translation_key": "input_58",
    },
    {
        "name": "Leaving water Add Heating setpoint upper",
        "address": 59,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_59",
        "entity_category": None,
        "translation_key": "input_59",
    },
    {
        "name": "Leaving water Add Cooling setpoint lower",
        "address": 60,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_60",
        "entity_category": None,
        "translation_key": "input_60",
    },
    {
        "name": "Leaving water Add Cooling setpoint upper",
        "address": 61,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_61",
        "entity_category": None,
        "translation_key": "input_61",
    },
    # Sonstige Status / Flags
    {
        "name": "Disinfection state",
        "address": 63,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:water-pump",
        "input_type": "input",
        "register_name": "input_63",
        "entity_category": None,
        "enum_map": {0: "Unsuccessful", 1: "Successful", 2: "Maintain", 3: "Heat Up"},
        "translation_key": "input_63",
    },
    {
        "name": "Holiday mode",
        "address": 64,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:beach",
        "input_type": "input",
        "register_name": "input_64",
        "device_class": "running",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_64",
    },
    {
        "name": "Demand response mode",
        "address": 65,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:lightning-bolt",
        "input_type": "input",
        "register_name": "input_65",
        "entity_category": None,
        "enum_map": {
            0: "Free",
            1: "Forced Off",
            2: "Forced On",
            3: "Recommended On",
            4: "Reduced",
        },
        "translation_key": "input_65",
    },
    {
        "name": "Bypass valve position",
        "address": 66,
        "unit": "%",
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:valve",
        "input_type": "input",
        "register_name": "input_66",
        "entity_category": None,
        "translation_key": "input_66",
    },
    {
        "name": "Tank valve position",
        "address": 67,
        "unit": "%",
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:valve",
        "input_type": "input",
        "register_name": "input_67",
        "entity_category": None,
        "translation_key": "input_67",
    },
    {
        "name": "Circulation pump speed",
        "address": 68,
        "unit": "L/min",
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:water-pump",
        "input_type": "input",
        "register_name": "input_68",
        "entity_category": None,
        "translation_key": "input_68",
    },
    {
        "name": "Mixed pump PWM",
        "address": 69,
        "unit": "%",
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:fan",
        "input_type": "input",
        "register_name": "input_69",
        "entity_category": None,
        "translation_key": "input_69",
    },
    {
        "name": "Direct pump PWM",
        "address": 70,
        "unit": "%",
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:fan",
        "input_type": "input",
        "register_name": "input_70",
        "entity_category": None,
        "translation_key": "input_70",
    },
    {
        "name": "Mixing valve position in mixing kit",
        "address": 71,
        "unit": "%",
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:valve",
        "input_type": "input",
        "register_name": "input_71",
        "entity_category": None,
        "translation_key": "input_71",
    },
    {
        "name": "Mixing Leaving water temperature in mixing kit",
        "address": 72,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_72",
        "entity_category": None,
        "translation_key": "input_72",
    },
    {
        "name": "Space heating/cooling target for Main zone in mixing kit",
        "address": 73,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_73",
        "entity_category": None,
        "translation_key": "input_73",
    },
    {
        "name": "Leaving water temperature prePHE outdoor",
        "address": 74,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_74",
        "entity_category": None,
        "translation_key": "input_74",
    },
    {
        "name": "Leaving water temperature Tank valve",
        "address": 75,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_75",
        "entity_category": None,
        "translation_key": "input_75",
    },
    {
        "name": "Domestic Hot Water Upper temperature",
        "address": 76,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_76",
        "entity_category": None,
        "translation_key": "input_76",
    },
    {
        "name": "Domestic Hot Water Lower temperature",
        "address": 77,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_77",
        "entity_category": None,
        "translation_key": "input_77",
    },
    {
        "name": "Water pressure",
        "address": 79,
        "unit": "bar",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:gauge",
        "input_type": "input",
        "register_name": "input_79",
        "entity_category": None,
        "translation_key": "input_79",
    },
    {
        "name": "Unit operation mode",
        "address": 83,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:cog",
        "input_type": "input",
        "register_name": "input_83",
        "entity_category": None,
        "translation_key": "input_83",
        "enum_map": {
            0: "Stop",
            1: "Tank Heat Up",
            2: "Space heating",
            3: "Space cooling",
            4: "Actuator",
        },
    },
    {
        "name": "Remote controller room temperature (Add)",
        "address": 78,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_78",
        "entity_category": None,
        "translation_key": "input_78",
    },
    {
        "name": "Space heating/cooling target for Main zone",
        "address": 80,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_80",
        "entity_category": None,
        "translation_key": "input_80",
    },
    {
        "name": "Space heating/cooling target for Add zone",
        "address": 81,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "input",
        "register_name": "input_81",
        "entity_category": None,
        "translation_key": "input_81",
    },
    {
        "name": "Abnormality counter (user)",
        "address": 82,
        "unit": None,
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:counter",
        "input_type": "input",
        "register_name": "input_82",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "input_82",
    },
    {
        "name": "Room Heating setpoint Lower limit",
        "address": 84,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer-low",
        "input_type": "input",
        "register_name": "input_84",
        "entity_category": None,
        "translation_key": "input_84",
    },
    {
        "name": "Room Heating setpoint Upper limit",
        "address": 85,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer-high",
        "input_type": "input",
        "register_name": "input_85",
        "entity_category": None,
        "translation_key": "input_85",
    },
    {
        "name": "Room Cooling setpoint Lower limit",
        "address": 86,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer-low",
        "input_type": "input",
        "register_name": "input_86",
        "entity_category": None,
        "translation_key": "input_86",
    },
    {
        "name": "Room Cooling setpoint Upper limit",
        "address": 87,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer-high",
        "input_type": "input",
        "register_name": "input_87",
        "entity_category": None,
        "translation_key": "input_87",
    },
]

# Holding Register (beschreibbare Register)
HOLDING_REGISTERS = [
    {
        "name": "Leaving water Main Heating setpoint",
        "address": 1,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_1",
        "min_value": 0,
        "max_value": 100,
        "step": 1,
        "translation_key": "holding_1",
    },
    {
        "name": "Leaving water Main Cooling setpoint",
        "address": 2,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_2",
        "min_value": 0,
        "max_value": 100,
        "step": 1,
        "translation_key": "holding_2",
    },
    {
        "name": "Room Thermostat Heating Setpoint Main",
        "address": 6,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_6",
        "min_value": 12,
        "max_value": 30,
        "step": 1,
        "translation_key": "holding_6",
    },
    {
        "name": "Room Thermostat Cooling Setpoint Main",
        "address": 7,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_7",
        "min_value": 12,
        "max_value": 35,
        "step": 1,
        "translation_key": "holding_7",
    },
    {
        "name": "Weather-dependent mode Heating Main",
        "address": 68,
        "min_v": 0,
        "max_v": 1,
        "step": 1,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:cog",
        "input_type": "holding",
        "register_name": "holding_68",
        "translation_key": "holding_68",
        "enum_map": {
            0: "Fixed",
            1: "Weather dependent",
        },
    },
    {
        "name": "Weather-dependent mode Cooling Main",
        "address": 69,
        "min_v": 0,
        "max_v": 1,
        "step": 1,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:cog",
        "input_type": "holding",
        "register_name": "holding_69",
        "translation_key": "holding_69",
        "enum_map": {
            0: "Fixed",
            1: "Weather dependent",
        },
    },
    {
        "name": "Thermostat Request Main",
        "address": 74,
        "min_v": 0,
        "max_v": 2,
        "step": 1,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:thermostat",
        "input_type": "holding",
        "register_name": "holding_74",
        "translation_key": "holding_74",
        "enum_map": {
            0: "None",
            1: "Heating",
            2: "Cooling",
        },
    },
    {
        "name": "Thermostat Request Additional",
        "address": 75,
        "min_v": 0,
        "max_v": 2,
        "step": 1,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:thermostat",
        "input_type": "holding",
        "register_name": "holding_75",
        "translation_key": "holding_75",
        "enum_map": {
            0: "None",
            1: "Heating",
            2: "Cooling",
        },
    },
    {
        "name": "DHW reheat setpoint",
        "address": 10,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_10",
        "min_value": 30,
        "max_value": 85,
        "step": 0.5,
        "translation_key": "holding_10",
    },
    {
        "name": "DHW boost setpoint (Powerful)",
        "address": 14,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_14",
        "min_value": 30,
        "max_value": 85,
        "step": 1,
        "translation_key": "holding_14",
    },
    {
        "name": "DHW Single Heat-up Setpoint (Manual)",
        "address": 16,
        "unit": "°C",
        "scale": 0.01,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_16",
        "min_value": 30,
        "max_value": 85,
        "step": 1,
        "translation_key": "holding_16",
    },
    {
        "name": "Weather-dependent mode Main LWT Heating setpoint offset",
        "address": 54,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_54",
        "min_value": -10,
        "max_value": 10,
        "step": 1,
        "translation_key": "holding_54",
    },
    {
        "name": "Weather-dependent mode Main LWT Cooling setpoint offset",
        "address": 55,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_55",
        "min_value": -10,
        "max_value": 10,
        "step": 1,
        "translation_key": "holding_55",
    },
    {
        "name": "Imposed power limit",
        "address": 58,
        "unit": "kW",
        "scale": 0.001,
        "dtype": "uint16",
        "icon": "mdi:lightning-bolt",
        "input_type": "holding",
        "register_name": "holding_58",
        "min_value": 0,
        "max_value": 20,
        "step": 0.5,
        "translation_key": "holding_58",
    },
    {
        "name": "Leaving water Add Heating setpoint",
        "address": 63,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_63",
        "min_value": 3,
        "max_value": 85,
        "step": 1,
        "translation_key": "holding_63",
    },
    {
        "name": "Leaving water Add Cooling setpoint",
        "address": 64,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_64",
        "min_value": 3,
        "max_value": 85,
        "step": 1,
        "translation_key": "holding_64",
    },
    {
        "name": "Weather-dependent mode Add LWT Heating setpoint offset",
        "address": 66,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_66",
        "min_value": -10,
        "max_value": 10,
        "step": 1,
        "translation_key": "holding_66",
    },
    {
        "name": "Weather-dependent mode Add LWT Cooling setpoint offset",
        "address": 67,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_67",
        "min_value": -10,
        "max_value": 10,
        "step": 1,
        "translation_key": "holding_67",
    },
    {
        "name": "Room Thermostat Heating Setpoint Main",
        "address": 76,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_76",
        "min_value": 12,
        "max_value": 30,
        "step": 1,
        "translation_key": "holding_76",
    },
    {
        "name": "Room Thermostat Cooling Setpoint Main",
        "address": 77,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_77",
        "min_value": 12,
        "max_value": 35,
        "step": 1,
        "translation_key": "holding_77",
    },
    {
        "name": "Room thermostat control Heating setpoint Add",
        "address": 78,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_78",
        "min_value": 12,
        "max_value": 30,
        "step": 1,
        "translation_key": "holding_78",
    },
    {
        "name": "Room thermostat control Cooling setpoint Add",
        "address": 79,
        "unit": "°C",
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:thermometer",
        "input_type": "holding",
        "register_name": "holding_79",
        "min_value": 12,
        "max_value": 35,
        "step": 1,
        "translation_key": "holding_79",
    },
]


SELECT_REGISTERS = [
    {
        "name": "Operation mode",
        "address": 3,
        "min_v": 0,
        "max_v": 2,
        "step": 1,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:cog",
        "input_type": "holding",
        "register_name": "holding_3",
        "translation_key": "holding_3",
        "enum_map": {0: "Auto", 1: "Heating", 2: "Cooling"},
    },
    {
        "name": "Quiet mode operation",
        "address": 9,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:cog",
        "input_type": "holding",
        "register_name": "holding_9",
        "translation_key": "holding_9",
        "enum_map": {0: "Off", 1: "On (Automatic)", 2: "On (Manual)"},
    },
    {
        "name": "Smart Grid Operation Mode",
        "address": 56,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:cog",
        "input_type": "holding",
        "register_name": "holding_56",
        "translation_key": "holding_56",
        "enum_map": {
            0: "Free running",
            1: "Forced off",
            2: "Recommended on",
            3: "Forced on",
        },
    },
    {
        "name": "DHW mode setting",
        "address": 80,
        "unit": None,
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:water-boiler",
        "input_type": "holding",
        "register_name": "holding_80",
        "translation_key": "holding_80",
        "enum_map": {
            0: "Reheat",
            1: "Schedule and reheat",
            2: "Scheduled",
            32766: "Off",
        },
    },
]

# Berechnete Sensoren

CALCULATED_SENSORS = [
    {
        "name": "Thermal Heat Output",
        "register_name": "thermal_heat_output",
        "unit": "W",
        "device_class": "power",
        "entity_category": None,
        "type": "heat_power",
        "translation_key": "thermal_heat_output",
    },
    {
        "name": "Coefficient of Performance",
        "register_name": "cop",
        "unit": "CoP",
        "device_class": None,
        "entity_category": None,
        "type": "cop",
        "translation_key": "cop",
    },
    {
        "name": "Delta-T",
        "register_name": "delta_t",
        "unit": "°C",
        "device_class": "temperature",
        "entity_category": None,
        "type": "delta_t",
        "translation_key": "delta_t",
    },
    {
        "name": "Last Compressor Run",
        "register_name": "last_compressor_run",
        "unit": None,
        "device_class": "timestamp",
        "type": "last_triggered",
        "entity_category": None,
        "trigger_register_name": "discrete_11",
        "translation_key": "last_compressor_run",
    },
    {
        "name": "Last Defrost",
        "register_name": "last_defrost",
        "unit": None,
        "device_class": "timestamp",
        "type": "last_triggered",
        "entity_category": None,
        "trigger_register_name": "discrete_17",
        "translation_key": "last_defrost",
    },
    {
        "name": "Last Booster Heater",
        "register_name": "last_booster_heater",
        "unit": None,
        "device_class": "timestamp",
        "type": "last_triggered",
        "entity_category": None,
        "trigger_register_name": "discrete_8",
        "translation_key": "last_booster_heater",
    },
    {
        "name": "Last DHW running",
        "register_name": "last_dhw_running",
        "unit": None,
        "device_class": "timestamp",
        "type": "last_triggered",
        "entity_category": None,
        "trigger_register_name": "discrete_19",
        "translation_key": "last_dhw_running",
    },
]

DISCRETE_INPUT_SENSORS = [
    # Status / Betriebszustände
    {
        "name": "Shut-off valve",
        "address": 1,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_1",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_1",
    },
    {
        "name": "Backup heater relay 1",
        "address": 2,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_2",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_2",
    },
    {
        "name": "Backup heater relay 2",
        "address": 3,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_3",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_3",
    },
    {
        "name": "Backup heater relay 3",
        "address": 4,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_4",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_4",
    },
    {
        "name": "Backup heater relay 4",
        "address": 5,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_5",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_5",
    },
    {
        "name": "Backup heater relay 5",
        "address": 6,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_6",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_6",
    },
    {
        "name": "Backup heater relay 6",
        "address": 7,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_7",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_7",
    },
    {
        "name": "Booster heater",
        "address": 8,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_8",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_8",
    },
    {
        "name": "Tank boiler",
        "address": 9,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_9",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_9",
    },
    {
        "name": "Bivalent",
        "address": 10,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_10",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_10",
    },
    {
        "name": "Compressor running",
        "address": 11,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_11",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_11",
    },
    {
        "name": "Quiet mode operation active",
        "address": 12,
        "device_class": None,
        "input_type": "discrete_input",
        "register_name": "discrete_12",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_12",
    },
    {
        "name": "Holiday mode active",
        "address": 13,
        "device_class": None,
        "input_type": "discrete_input",
        "register_name": "discrete_13",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_13",
    },
    {
        "name": "Antifrost status",
        "address": 14,
        "device_class": None,
        "input_type": "discrete_input",
        "register_name": "discrete_14",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_14",
    },
    {
        "name": "Water pipe freeze prevention status",
        "address": 15,
        "device_class": None,
        "input_type": "discrete_input",
        "register_name": "discrete_15",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_15",
    },
    {
        "name": "Disinfection operation",
        "address": 16,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_16",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_16",
    },
    {
        "name": "Defrost",
        "address": 17,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_17",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_17",
    },
    {
        "name": "Hot start",
        "address": 18,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_18",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_18",
    },
    {
        "name": "DHW running",
        "address": 19,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_19",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_19",
    },
    {
        "name": "Main zone running",
        "address": 20,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_20",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_20",
    },
    {
        "name": "Additional zone running",
        "address": 21,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_21",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_21",
    },
    {
        "name": "Powerful tank heat up request",
        "address": 22,
        "device_class": None,
        "input_type": "discrete_input",
        "register_name": "discrete_22",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_22",
    },
    {
        "name": "Manual tank heat up request",
        "address": 23,
        "device_class": None,
        "input_type": "discrete_input",
        "register_name": "discrete_23",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_23",
    },
    {
        "name": "Emergency active",
        "address": 24,
        "device_class": "problem",
        "input_type": "discrete_input",
        "register_name": "discrete_24",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_24",
    },
    {
        "name": "Circulation pump running",
        "address": 25,
        "device_class": "running",
        "input_type": "discrete_input",
        "register_name": "discrete_25",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_25",
    },
    {
        "name": "Imposed limit acceptance",
        "address": 26,
        "device_class": None,
        "input_type": "discrete_input",
        "register_name": "discrete_26",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "translation_key": "discrete_26",
    },
]

# Holding Register Switches (beschreibbare Register mit On/Off Funktionalität)

HOLDING_SWITCHES = [
    {
        "name": "Space heating/cooling - Select Entity",
        "address": 4,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:thermostat",
        "input_type": "holding",
        "register_name": "holding_4",
        "entity_category": None,
        "translation_key": "holding_4",
        "enum_map": {0: "OFF", 1: "ON"},
    },
    {
        "name": "DHW booster mode (Powerful)",
        "address": 13,
        "unit": None,
        "scale": 1,
        "dtype": "uint16",
        "icon": "mdi:power",
        "input_type": "holding",
        "register_name": "holding_13",
        "entity_category": None,
        "translation_key": "holding_13",
        "enum_map": {0: "Off", 1: "On (Powerful)"},
    },
    {
        "name": "DHW Single heat-up ON/OFF (Manual)",
        "address": 15,
        "unit": None,
        "scale": 1,
        "dtype": "int16",
        "icon": "mdi:power",
        "input_type": "holding",
        "register_name": "holding_15",
        "entity_category": None,
        "translation_key": "holding_15",
        "enum_map": {0: "Off", 1: "On"},
    },
]

# Alle Coil-Register aus 7.2.4 Daikin Configuration reference guide

COIL_SENSORS = [
    {
        "name": "Domestic Hot Water ON/OFF",
        "address": 1,
        "device_class": "switch",
        "input_type": "coil",
        "register_name": "coil_1",
        "entity_category": None,
        "translation_key": "coil_1",
    },
    {
        "name": "Main zone ON/OFF",
        "address": 2,
        "device_class": "switch",
        "input_type": "coil",
        "register_name": "coil_2",
        "entity_category": None,
        "translation_key": "coil_2",
    },
    {
        "name": "Additional zone ON/OFF",
        "address": 3,
        "device_class": "switch",
        "input_type": "coil",
        "register_name": "coil_3",
        "entity_category": None,
        "translation_key": "coil_3",
    },
]

# Register constants for Daikin Altherma 4
REGISTER_OPERATION_MODE = "holding_3"  # Operation mode
REGISTER_CURRENT_TEMP = (
    "input_40"  # Leaving water temperature PHE (plate heat exchanger)
)
REGISTER_OFFSET_HEATING = (
    "holding_54"  # Weather-dependent mode Main LWT Heating setpoint offset
)
REGISTER_OFFSET_COOLING = (
    "holding_53"  # Weather-dependent mode Main LWT Cooling setpoint offset
)
REGISTER_QUIET_MODE = "holding_9"  # Quiet mode operation
REGISTER_COMPRESSOR = "input_31"  # Compressor status

# DHW Control constants
REGISTER_DHW_HVAC_MODE = "coil_1"  # Domestic Hot Water
REGISTER_DHW_SETPOINT = "holding_10"  # DHW Single heat-up setpoint (Manual)
REGISTER_DHW_RUNNING = "discrete_19"  # DHW running status
REGISTER_DHW_TEMP = "input_43"  # DHW temperature

# DHW Booster Control constants
REGISTER_DHW_BOOSTER_HVAC_MODE = "holding_13"  # Domestic Hot Water
REGISTER_DHW_BOOSTER_SETPOINT = "holding_14"  # DHW Single heat-up setpoint (Manual)
REGISTER_DHW_BOOSTER_RUNNING = "discrete_19"  # DHW running status
REGISTER_DHW_BOOSTER_TEMP = "input_43"  # DHW temperature

# Fan mode constants (quiet mode)
FAN_OFF = "OFF"
FAN_AUTO = "Auto"
FAN_MANUAL = "Manual"
FAN_FAN_OFF = "Off"

# HVAC mode constants
HVAC_OFF = 0
HVAC_HEAT = 1
HVAC_COOL = 2

# DHW constants
DHW_OFF = False
DHW_ON = True
