"""Register constants using dataclasses for Daikin Altherma 4 Modbus integration."""

try:
    from homeassistant.const import EntityCategory
except ImportError:
    # Fallback for testing when homeassistant is not available
    from enum import StrEnum

    class EntityCategory(StrEnum):
        DIAGNOSTIC = "diagnostic"


from .register_types import (
    CalculatedRegister,
    NumberRegister,
    SelectRegister,
    SensorRegister,
    SwitchRegister,
)

# Device information constants
INPUT_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "input_registers")},
    "translation_key": "daikin_altherma_modbus_input_registers",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

HOLDING_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "holding_registers")},
    "translation_key": "daikin_altherma_modbus_holding_registers",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

CALCULATED_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "calculated_sensors")},
    "translation_key": "daikin_altherma_modbus_calculated_sensors",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

DISCRETE_INPUT_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "discrete_input_registers")},
    "translation_key": "daikin_altherma_modbus_discrete_input_registers",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

COIL_DEVICE_INFO = {
    "identifiers": {("daikin_altherma_modbus", "coil_registers")},
    "translation_key": "daikin_altherma_modbus_coil_registers",
    "manufacturer": "Daikin",
    "model": "Altherma 4",
}

# Input Registers using dataclasses
INPUT_REGISTERS = [
    # Fehler / Status (21-23)
    SensorRegister(
        name="Unit abnormality",
        address=21,
        input_type="input",
        register_name="input_21",
        icon="mdi:alert-circle",
        entity_category=EntityCategory.DIAGNOSTIC,
        dtype="int16",
        enum_map={0: "no_error", 1: "fault", 2: "warning"},
        translation_key="input_21",
    ),
    SensorRegister(
        name="Unit abnormality code",
        address=22,
        input_type="input",
        register_name="input_22",
        icon="mdi:alert-circle",
        entity_category=EntityCategory.DIAGNOSTIC,
        dtype="string",
        count=1,
        translation_key="input_22",
    ),
    SensorRegister(
        name="Unit abnormality sub code",
        address=23,
        input_type="input",
        register_name="input_23",
        icon="mdi:alert-circle",
        entity_category=EntityCategory.DIAGNOSTIC,
        dtype="uint16",
        enum_map={**{i: f"error_{i}" for i in range(100)}, 32766: "no_error"},
        translation_key="input_23",
    ),
    # Betriebszustände (30-38)
    SensorRegister(
        name="Circulation pump running",
        address=30,
        input_type="input",
        register_name="input_30",
        device_class="running",
        icon="mdi:pump",
        dtype="uint16",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="input_30",
    ),
    SensorRegister(
        name="Compressor run",
        address=31,
        input_type="input",
        register_name="input_31",
        device_class="running",
        icon="mdi:compressor",
        dtype="uint16",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="input_31",
    ),
    SensorRegister(
        name="Booster heater run",
        address=32,
        input_type="input",
        register_name="input_32",
        device_class="running",
        icon="mdi:heater",
        dtype="uint16",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="input_32",
    ),
    SensorRegister(
        name="Disinfection operation",
        address=33,
        input_type="input",
        register_name="input_33",
        device_class="running",
        icon="mdi:water-boiler",
        dtype="uint16",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="input_33",
    ),
    SensorRegister(
        name="Defrost/Restart",
        address=35,
        input_type="input",
        register_name="input_35",
        device_class="running",
        icon="mdi:snowflake-melt",
        dtype="uint16",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="input_35",
    ),
    SensorRegister(
        name="Hot start",
        address=36,
        input_type="input",
        register_name="input_36",
        device_class="running",
        icon="mdi:fire",
        dtype="uint16",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="input_36",
    ),
    SensorRegister(
        name="3-way valve",
        address=37,
        input_type="input",
        register_name="input_37",
        icon="mdi:pipe-valve",
        dtype="uint16",
        enum_map={0: "Space heating", 1: "DHW"},
        translation_key="input_37",
    ),
    SensorRegister(
        name="Operation mode",
        address=38,
        input_type="input",
        register_name="input_38",
        icon="mdi:thermostat",
        dtype="uint16",
        enum_map={0: "None", 1: "Heating", 2: "Cooling"},
        translation_key="input_38",
    ),
    # Temperaturen (40-45)
    SensorRegister(
        name="Leaving water temperature PHE",
        address=40,
        input_type="input",
        register_name="input_40",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_40",
    ),
    SensorRegister(
        name="Leaving water temperature BUH",
        address=41,
        input_type="input",
        register_name="input_41",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_41",
    ),
    SensorRegister(
        name="Return water temperature",
        address=42,
        input_type="input",
        register_name="input_42",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_42",
    ),
    SensorRegister(
        name="Domestic Hot Water temperature",
        address=43,
        input_type="input",
        register_name="input_43",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_43",
    ),
    SensorRegister(
        name="Outside air temperature",
        address=44,
        input_type="input",
        register_name="input_44",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_44",
    ),
    SensorRegister(
        name="Liquid refrigerant temperature",
        address=45,
        input_type="input",
        register_name="input_45",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_45",
    ),
    # Flow und Leistung (49-53)
    SensorRegister(
        name="Flow rate",
        address=49,
        input_type="input",
        register_name="input_49",
        unit="L/min",
        scale=0.01,
        dtype="uint16",
        icon="mdi:water",
        translation_key="input_49",
    ),
    SensorRegister(
        name="Remote control room temperature (Main)",
        address=50,
        input_type="input",
        register_name="input_50",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_50",
    ),
    SensorRegister(
        name="Heat pump power consumption",
        address=51,
        input_type="input",
        register_name="input_51",
        unit="W",
        scale=10,
        dtype="uint16",
        icon="mdi:flash",
        translation_key="input_51",
    ),
    SensorRegister(
        name="DHW normal operation",
        address=52,
        input_type="input",
        register_name="input_52",
        icon="mdi:information",
        dtype="uint16",
        enum_map={0: "Idle/Buffering", 1: "Operation"},
        translation_key="input_52",
    ),
    SensorRegister(
        name="Space heating/cooling normal operation",
        address=53,
        input_type="input",
        register_name="input_53",
        icon="mdi:information",
        dtype="uint16",
        enum_map={0: "Idle/Buffering", 1: "Operation"},
        translation_key="input_53",
    ),
    # Setpoints Main (54-57)
    SensorRegister(
        name="Leaving water Main Heating setpoint lower",
        address=54,
        input_type="input",
        register_name="input_54",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_54",
    ),
    SensorRegister(
        name="Leaving water Main Heating setpoint upper",
        address=55,
        input_type="input",
        register_name="input_55",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_55",
    ),
    SensorRegister(
        name="Leaving water Main Cooling setpoint lower",
        address=56,
        input_type="input",
        register_name="input_56",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_56",
    ),
    SensorRegister(
        name="Leaving water Main Cooling setpoint upper",
        address=57,
        input_type="input",
        register_name="input_57",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_57",
    ),
    # Setpoints Add (58-61)
    SensorRegister(
        name="Leaving water Add Heating setpoint lower",
        address=58,
        input_type="input",
        register_name="input_58",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_58",
    ),
    SensorRegister(
        name="Leaving water Add Heating setpoint upper",
        address=59,
        input_type="input",
        register_name="input_59",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_59",
    ),
    SensorRegister(
        name="Leaving water Add Cooling setpoint lower",
        address=60,
        input_type="input",
        register_name="input_60",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_60",
    ),
    SensorRegister(
        name="Leaving water Add Cooling setpoint upper",
        address=61,
        input_type="input",
        register_name="input_61",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_61",
    ),
    # Status (63-70)
    SensorRegister(
        name="Disinfection state",
        address=63,
        input_type="input",
        register_name="input_63",
        icon="mdi:water-pump",
        dtype="uint16",
        enum_map={0: "Unsuccessful", 1: "Successful", 2: "Maintain", 3: "Heat Up"},
        translation_key="input_63",
    ),
    SensorRegister(
        name="Holiday mode",
        address=64,
        input_type="input",
        register_name="input_64",
        device_class="running",
        icon="mdi:beach",
        dtype="uint16",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="input_64",
    ),
    SensorRegister(
        name="Demand response mode",
        address=65,
        input_type="input",
        register_name="input_65",
        icon="mdi:lightning-bolt",
        dtype="uint16",
        enum_map={
            0: "Free",
            1: "Forced Off",
            2: "Forced On",
            3: "Recommended On",
            4: "Reduced",
        },
        translation_key="input_65",
    ),
    SensorRegister(
        name="Bypass valve position",
        address=66,
        input_type="input",
        register_name="input_66",
        unit="%",
        dtype="uint16",
        icon="mdi:valve",
        translation_key="input_66",
    ),
    SensorRegister(
        name="Tank valve position",
        address=67,
        input_type="input",
        register_name="input_67",
        unit="%",
        dtype="uint16",
        icon="mdi:valve",
        translation_key="input_67",
    ),
    SensorRegister(
        name="Circulation pump speed",
        address=68,
        input_type="input",
        register_name="input_68",
        unit="L/min",
        dtype="uint16",
        icon="mdi:water-pump",
        translation_key="input_68",
    ),
    SensorRegister(
        name="Mixed pump PWM",
        address=69,
        input_type="input",
        register_name="input_69",
        unit="%",
        dtype="uint16",
        icon="mdi:fan",
        translation_key="input_69",
    ),
    SensorRegister(
        name="Direct pump PWM",
        address=70,
        input_type="input",
        register_name="input_70",
        unit="%",
        dtype="uint16",
        icon="mdi:fan",
        translation_key="input_70",
    ),
    # Mixing kit (71-75)
    SensorRegister(
        name="Mixing valve position in mixing kit",
        address=71,
        input_type="input",
        register_name="input_71",
        unit="%",
        dtype="uint16",
        icon="mdi:valve",
        translation_key="input_71",
    ),
    SensorRegister(
        name="Mixing Leaving water temperature in mixing kit",
        address=72,
        input_type="input",
        register_name="input_72",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_72",
    ),
    SensorRegister(
        name="Space heating/cooling target for Main zone in mixing kit",
        address=73,
        input_type="input",
        register_name="input_73",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_73",
    ),
    SensorRegister(
        name="Leaving water temperature prePHE outdoor",
        address=74,
        input_type="input",
        register_name="input_74",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_74",
    ),
    SensorRegister(
        name="Leaving water temperature Tank valve",
        address=75,
        input_type="input",
        register_name="input_75",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_75",
    ),
    # DHW Temperaturen (76-79)
    SensorRegister(
        name="Domestic Hot Water Upper temperature",
        address=76,
        input_type="input",
        register_name="input_76",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_76",
    ),
    SensorRegister(
        name="Domestic Hot Water Lower temperature",
        address=77,
        input_type="input",
        register_name="input_77",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_77",
    ),
    SensorRegister(
        name="Remote controller room temperature (Add)",
        address=78,
        input_type="input",
        register_name="input_78",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_78",
    ),
    SensorRegister(
        name="Water pressure",
        address=79,
        input_type="input",
        register_name="input_79",
        unit="bar",
        scale=0.01,
        dtype="int16",
        icon="mdi:gauge",
        translation_key="input_79",
    ),
    # Targets und Limits (80-87)
    SensorRegister(
        name="Space heating/cooling target for Main zone",
        address=80,
        input_type="input",
        register_name="input_80",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_80",
    ),
    SensorRegister(
        name="Space heating/cooling target for Add zone",
        address=81,
        input_type="input",
        register_name="input_81",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer",
        translation_key="input_81",
    ),
    SensorRegister(
        name="Abnormality counter (user)",
        address=82,
        input_type="input",
        register_name="input_82",
        icon="mdi:counter",
        dtype="int16",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="input_82",
    ),
    SensorRegister(
        name="Unit operation mode",
        address=83,
        input_type="input",
        register_name="input_83",
        icon="mdi:cog",
        dtype="uint16",
        enum_map={
            0: "Stop",
            1: "Tank Heat Up",
            2: "Space heating",
            3: "Space cooling",
            4: "Actuator",
        },
        translation_key="input_83",
    ),
    SensorRegister(
        name="Room Heating setpoint Lower limit",
        address=84,
        input_type="input",
        register_name="input_84",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer-low",
        translation_key="input_84",
    ),
    SensorRegister(
        name="Room Heating setpoint Upper limit",
        address=85,
        input_type="input",
        register_name="input_85",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer-high",
        translation_key="input_85",
    ),
    SensorRegister(
        name="Room Cooling setpoint Lower limit",
        address=86,
        input_type="input",
        register_name="input_86",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer-low",
        translation_key="input_86",
    ),
    SensorRegister(
        name="Room Cooling setpoint Upper limit",
        address=87,
        input_type="input",
        register_name="input_87",
        unit="°C",
        scale=0.01,
        dtype="int16",
        icon="mdi:thermometer-high",
        translation_key="input_87",
    ),
]

# Holding Registers using dataclasses
HOLDING_REGISTERS = [
    NumberRegister(
        name="Leaving water Main Heating setpoint",
        address=1,
        input_type="holding",
        register_name="holding_1",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=5,
        max_value=60,
        step=0.1,
        translation_key="holding_1",
    ),
    NumberRegister(
        name="Leaving water Main Cooling setpoint",
        address=2,
        input_type="holding",
        register_name="holding_2",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=5,
        max_value=60,
        step=0.1,
        translation_key="holding_2",
    ),
    SelectRegister(
        name="Operation mode select",
        address=3,
        input_type="holding",
        register_name="holding_3",
        enum_map={0: "Off", 1: "Heating", 2: "Cooling"},
        translation_key="holding_3",
    ),
    SwitchRegister(
        name="Space heating/cooling ON/OFF",
        address=4,
        input_type="holding",
        register_name="holding_4",
        enum_map={0: "OFF", 1: "ON"},
        translation_key="holding_4",
    ),
    NumberRegister(
        name="Room Thermostat Heating Setpoint Main",
        address=6,
        input_type="holding",
        register_name="holding_6",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=12,
        max_value=30,
        step=0.1,
        translation_key="holding_6",
    ),
    NumberRegister(
        name="Room Thermostat Cooling Setpoint Main",
        address=7,
        input_type="holding",
        register_name="holding_7",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=12,
        max_value=35,
        step=0.1,
        translation_key="holding_7",
    ),
    SelectRegister(
        name="Quiet mode operation",
        address=9,
        input_type="holding",
        register_name="holding_9",
        enum_map={0: "Off", 1: "On (Automatic)", 2: "On (Manual)"},
        translation_key="holding_9",
    ),
    NumberRegister(
        name="DHW reheat setpoint",
        address=10,
        input_type="holding",
        register_name="holding_10",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=30,
        max_value=85,
        step=0.5,
        translation_key="holding_10",
    ),
    SwitchRegister(
        name="DHW booster mode ON/OFF (Powerful)",
        address=13,
        input_type="holding",
        register_name="holding_13",
        enum_map={0: "Off", 1: "On (Powerful)"},
        translation_key="holding_13",
    ),
    NumberRegister(
        name="DHW boost setpoint (Powerful)",
        address=14,
        input_type="holding",
        register_name="holding_14",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=30,
        max_value=85,
        step=0.5,
        translation_key="holding_14",
    ),
    SwitchRegister(
        name="DHW Single heat-up ON/OFF (Manual)",
        address=15,
        input_type="holding",
        register_name="holding_15",
        enum_map={0: "Off", 1: "On"},
        translation_key="holding_15",
    ),
    NumberRegister(
        name="DHW Single Heat-up Setpoint (Manual)",
        address=16,
        input_type="holding",
        register_name="holding_16",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=30,
        max_value=85,
        step=0.5,
        translation_key="holding_16",
    ),
    NumberRegister(
        name="Weather-dependent mode Main LWT Heating setpoint offset",
        address=54,
        input_type="holding",
        register_name="holding_54",
        unit="K",
        scale=0.01,
        dtype="int16",
        min_value=-10,
        max_value=10,
        step=0.1,
        translation_key="holding_54",
    ),
    NumberRegister(
        name="Weather-dependent mode Main LWT Cooling setpoint offset",
        address=55,
        input_type="holding",
        register_name="holding_55",
        unit="K",
        scale=0.01,
        dtype="int16",
        min_value=-10,
        max_value=10,
        step=0.1,
        translation_key="holding_55",
    ),
    SelectRegister(
        name="Smart Grid Operation Mode",
        address=56,
        input_type="holding",
        register_name="holding_56",
        enum_map={
            0: "Free running",
            1: "Forced off",
            2: "Recommended on",
            3: "Forced on",
        },
        translation_key="holding_56",
    ),
    NumberRegister(
        name="Imposed power limit",
        address=58,
        input_type="holding",
        register_name="holding_58",
        unit="kW",
        scale=0.001,
        dtype="uint16",
        min_value=0,
        max_value=20,
        step=0.5,
        translation_key="holding_58",
    ),
    NumberRegister(
        name="Leaving water Add Heating setpoint",
        address=63,
        input_type="holding",
        register_name="holding_63",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=3,
        max_value=85,
        step=0.1,
        translation_key="holding_63",
    ),
    NumberRegister(
        name="Leaving water Add Cooling setpoint",
        address=64,
        input_type="holding",
        register_name="holding_64",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=3,
        max_value=85,
        step=0.1,
        translation_key="holding_64",
    ),
    NumberRegister(
        name="Weather-dependent mode Add LWT Heating setpoint offset",
        address=66,
        input_type="holding",
        register_name="holding_66",
        unit="K",
        scale=0.01,
        dtype="int16",
        min_value=-10,
        max_value=10,
        step=0.1,
        translation_key="holding_66",
    ),
    NumberRegister(
        name="Weather-dependent mode Add LWT Cooling setpoint offset",
        address=67,
        input_type="holding",
        register_name="holding_67",
        unit="K",
        scale=0.01,
        dtype="int16",
        min_value=-10,
        max_value=10,
        step=0.1,
        translation_key="holding_67",
    ),
    SelectRegister(
        name="Weather-dependent mode Heating Main",
        address=68,
        input_type="holding",
        register_name="holding_68",
        enum_map={0: "Fixed", 1: "Weather dependent"},
        translation_key="holding_68",
    ),
    SelectRegister(
        name="Weather-dependent mode Cooling Main",
        address=69,
        input_type="holding",
        register_name="holding_69",
        enum_map={0: "Fixed", 1: "Weather dependent"},
        translation_key="holding_69",
    ),
    SelectRegister(
        name="Thermostat Request Main",
        address=74,
        input_type="holding",
        register_name="holding_74",
        enum_map={0: "None", 1: "Heating", 2: "Cooling"},
        translation_key="holding_74",
    ),
    SelectRegister(
        name="Thermostat Request Add",
        address=75,
        input_type="holding",
        register_name="holding_75",
        enum_map={0: "None", 1: "Heating", 2: "Cooling"},
        translation_key="holding_75",
    ),
    NumberRegister(
        name="Room Thermostat control Heating Setpoint Main",
        address=76,
        input_type="holding",
        register_name="holding_76",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=12,
        max_value=30,
        step=0.1,
        translation_key="holding_76",
    ),
    NumberRegister(
        name="Room Thermostat control Cooling Setpoint Main",
        address=77,
        input_type="holding",
        register_name="holding_77",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=12,
        max_value=35,
        step=0.1,
        translation_key="holding_77",
    ),
    NumberRegister(
        name="Room thermostat control Heating setpoint Add",
        address=78,
        input_type="holding",
        register_name="holding_78",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=12,
        max_value=30,
        step=0.1,
        translation_key="holding_78",
    ),
    NumberRegister(
        name="Room thermostat control Cooling setpoint Add",
        address=79,
        input_type="holding",
        register_name="holding_79",
        unit="°C",
        scale=0.01,
        dtype="int16",
        min_value=12,
        max_value=35,
        step=0.1,
        translation_key="holding_79",
    ),
    SelectRegister(
        name="DHW mode setting",
        address=80,
        input_type="holding",
        register_name="holding_80",
        enum_map={
            0: "Reheat",
            1: "Schedule and reheat",
            2: "Scheduled",
            32766: "Off",
        },
        translation_key="holding_80",
    ),
]

# Discrete Input Sensors using dataclasses
DISCRETE_REGISTERS = [
    SensorRegister(
        name="Shut-off valve",
        address=1,
        input_type="discrete",
        register_name="discrete_1",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_1",
    ),
    SensorRegister(
        name="Backup heater relay 1",
        address=2,
        input_type="discrete",
        register_name="discrete_2",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_2",
    ),
    SensorRegister(
        name="Backup heater relay 2",
        address=3,
        input_type="discrete",
        register_name="discrete_3",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_3",
    ),
    SensorRegister(
        name="Backup heater relay 3",
        address=4,
        input_type="discrete",
        register_name="discrete_4",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_4",
    ),
    SensorRegister(
        name="Backup heater relay 4",
        address=5,
        input_type="discrete",
        register_name="discrete_5",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_5",
    ),
    SensorRegister(
        name="Backup heater relay 5",
        address=6,
        input_type="discrete",
        register_name="discrete_6",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_6",
    ),
    SensorRegister(
        name="Backup heater relay 6",
        address=7,
        input_type="discrete",
        register_name="discrete_7",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_7",
    ),
    SensorRegister(
        name="Booster heater",
        address=8,
        input_type="discrete",
        register_name="discrete_8",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_8",
    ),
    SensorRegister(
        name="Tank boiler",
        address=9,
        input_type="discrete",
        register_name="discrete_9",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_9",
    ),
    SensorRegister(
        name="Bivalent",
        address=10,
        input_type="discrete",
        register_name="discrete_10",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_10",
    ),
    SensorRegister(
        name="Compressor running",
        address=11,
        input_type="discrete",
        register_name="discrete_11",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_11",
    ),
    SensorRegister(
        name="Quiet mode operation active",
        address=12,
        input_type="discrete",
        register_name="discrete_12",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_12",
    ),
    SensorRegister(
        name="Holiday mode active",
        address=13,
        input_type="discrete",
        register_name="discrete_13",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_13",
    ),
    SensorRegister(
        name="Antifrost status",
        address=14,
        input_type="discrete",
        register_name="discrete_14",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_14",
    ),
    SensorRegister(
        name="Water pipe freeze prevention status",
        address=15,
        input_type="discrete",
        register_name="discrete_15",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_15",
    ),
    SensorRegister(
        name="Disinfection operation",
        address=16,
        input_type="discrete",
        register_name="discrete_16",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_16",
    ),
    SensorRegister(
        name="Defrost",
        address=17,
        input_type="discrete",
        register_name="discrete_17",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_17",
    ),
    SensorRegister(
        name="Hot start",
        address=18,
        input_type="discrete",
        register_name="discrete_18",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_18",
    ),
    SensorRegister(
        name="DHW running",
        address=19,
        input_type="discrete",
        register_name="discrete_19",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_19",
    ),
    SensorRegister(
        name="Main zone running",
        address=20,
        input_type="discrete",
        register_name="discrete_20",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_20",
    ),
    SensorRegister(
        name="Additional zone running",
        address=21,
        input_type="discrete",
        register_name="discrete_21",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_21",
    ),
    SensorRegister(
        name="Powerful tank heat up request",
        address=22,
        input_type="discrete",
        register_name="discrete_22",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_22",
    ),
    SensorRegister(
        name="Manual tank heat up request",
        address=23,
        input_type="discrete",
        register_name="discrete_23",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_23",
    ),
    SensorRegister(
        name="Emergency active",
        address=24,
        input_type="discrete",
        register_name="discrete_24",
        device_class="problem",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_24",
    ),
    SensorRegister(
        name="Circulation pump running",
        address=25,
        input_type="discrete",
        register_name="discrete_25",
        device_class="running",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_25",
    ),
    SensorRegister(
        name="Imposed limit acceptance",
        address=26,
        input_type="discrete",
        register_name="discrete_26",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="discrete_26",
    ),
]

# Coil Registers using dataclasses
COIL_REGISTERS = [
    SwitchRegister(
        name="Domestic Hot Water ON/OFF",
        address=1,
        input_type="coil",
        register_name="coil_1",
        translation_key="coil_1",
    ),
    SwitchRegister(
        name="Main zone ON/OFF",
        address=2,
        input_type="coil",
        register_name="coil_2",
        translation_key="coil_2",
    ),
    SwitchRegister(
        name="Additional zone ON/OFF",
        address=3,
        input_type="coil",
        register_name="coil_3",
        translation_key="coil_3",
    ),
]

# Calculated Sensors using dataclasses
CALCULATED_SENSORS = [
    CalculatedRegister(
        name="Thermal Heat Output",
        address=0,
        input_type="calculated",
        register_name="thermal_heat_output",
        calc_type="heat_power",
        unit="W",
        device_class="power",
        translation_key="thermal_heat_output",
    ),
    CalculatedRegister(
        name="Coefficient of Performance",
        address=0,
        input_type="calculated",
        register_name="cop",
        calc_type="cop",
        unit="CoP",
        translation_key="cop",
    ),
    CalculatedRegister(
        name="Last Compressor Run",
        address=0,
        input_type="calculated",
        register_name="last_compressor_run",
        calc_type="last_triggered",
        unit="",
        device_class="timestamp",
        trigger_register_name="discrete_11",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="last_compressor_run",
    ),
    CalculatedRegister(
        name="Last Defrost",
        address=0,
        input_type="calculated",
        register_name="last_defrost",
        calc_type="last_triggered",
        unit="",
        device_class="timestamp",
        trigger_register_name="discrete_17",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="last_defrost",
    ),
    CalculatedRegister(
        name="Last Booster Heater",
        address=0,
        input_type="calculated",
        register_name="last_booster_heater",
        calc_type="last_triggered",
        unit="",
        device_class="timestamp",
        trigger_register_name="discrete_8",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="last_booster_heater",
    ),
    CalculatedRegister(
        name="Last DHW running",
        address=0,
        input_type="calculated",
        register_name="last_dhw_running",
        calc_type="last_triggered",
        unit="",
        device_class="timestamp",
        trigger_register_name="discrete_19",
        entity_category=EntityCategory.DIAGNOSTIC,
        translation_key="last_dhw_running",
    ),
    CalculatedRegister(
        name="Delta-T",
        address=0,
        input_type="calculated",
        register_name="delta_t",
        calc_type="delta_t",
        unit="K",
        device_class="temperature",
        translation_key="delta_t",
    ),
]
